apiVersion: apps/v1
kind: Deployment
metadata:
  name: overseerr
  namespace: servarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: overseerr
  template:
    metadata:
      labels:
        app: overseerr
    spec:
      containers:
      - name: overseerr
        image: lscr.io/linuxserver/overseerr:latest
        ports:
        - containerPort: 5055
        volumeMounts:
        - name: overseerr-storage
          mountPath: /config
        resources:
          requests:
            cpu: 500m
            memory: 256Mi
          limits:
            cpu: 1000m
            memory: 1024Mi   
      volumes:
      - name: overseerr-storage
        persistentVolumeClaim:
          claimName: overseerr-pvc