apiVersion: v1
kind: PersistentVolume
metadata:
  name: 4k-tv-pv
  namespace: servarr
  labels:
    type: local
spec:
  storageClassName: 4k-tv
  capacity:
    storage: 180Ti
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/unraid/4k-tv"
  persistentVolumeReclaimPolicy: Retain