apiVersion: v1
kind: PersistentVolume
metadata:
  name: appdatak8-pv
  namespace: servarr
  labels:
    type: local
spec:
  storageClassName: appdatak8
  capacity:
    storage: 180Ti
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/unraid/appdatak8"
  persistentVolumeReclaimPolicy: Retain