apiVersion: v1
kind: PersistentVolume
metadata:
  name: bazarr-pv
  namespace: servarr
  labels:
    type: local
spec:
  storageClassName: bazarr
  capacity:
    storage: 180Ti
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/unraid/appdatak8/k3s/bazarr"
  persistentVolumeReclaimPolicy: Retain