apiVersion: v1
kind: PersistentVolume
metadata:
  name: code-server-pv
  namespace: servarr
  labels:
    type: local
spec:
  storageClassName: code-server
  capacity:
    storage: 180Ti
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/unraid/appdatak8/k3s/code-server"
  persistentVolumeReclaimPolicy: Retain