apiVersion: v1
kind: PersistentVolume
metadata:
  name: lidarr-pv
  namespace: servarr
  labels:
    type: local
spec:
  storageClassName: lidarr
  capacity:
    storage: 180Ti
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/unraid/appdatak8/k3s/lidarr"
  persistentVolumeReclaimPolicy: Retain