apiVersion: v1
kind: PersistentVolume
metadata:
  name: movies-pv
  namespace: servarr
  labels:
    type: local
spec:
  storageClassName: movies
  capacity:
    storage: 180Ti
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/unraid/movies"
  persistentVolumeReclaimPolicy: Retain