apiVersion: v1
kind: PersistentVolume
metadata:
  name: overseerr-pv
  namespace: servarr
  labels:
    type: local
spec:
  storageClassName: overseerr
  capacity:
    storage: 180Ti
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/unraid/appdatak8/k3s/overseerr"
  persistentVolumeReclaimPolicy: Retain