apiVersion: v1
kind: PersistentVolume
metadata:
  name: prowlarr-pv
  namespace: servarr
  labels:
    type: local
spec:
  storageClassName: prowlarr
  capacity:
    storage: 180Ti
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/unraid/appdatak8/k3s/prowlarr"
  persistentVolumeReclaimPolicy: Retain