apiVersion: v1
kind: PersistentVolume
metadata:
  name: radarr-pv
  namespace: servarr
  labels:
    type: local
spec:
  storageClassName: radarr
  capacity:
    storage: 180Ti
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/unraid/appdatak8/k3s/radarr"
  persistentVolumeReclaimPolicy: Retain