apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarr-pv
  namespace: servarr
  labels:
    type: local
spec:
  storageClassName: sonarr
  capacity:
    storage: 180Ti
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/unraid/appdatak8/k3s/sonarr"
  persistentVolumeReclaimPolicy: Retain