apiVersion: v1
kind: PersistentVolume
metadata:
  name: speed-test-pv
  namespace: servarr
  labels:
    type: local
spec:
  storageClassName: speed-test
  capacity:
    storage: 180Ti
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/unraid/appdatak8/k3s/speed-test"
  persistentVolumeReclaimPolicy: Retain