apiVersion: v1
kind: PersistentVolume
metadata:
  name: tv-pv
  namespace: servarr
  labels:
    type: local
spec:
  storageClassName: tv
  capacity:
    storage: 180Ti
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/unraid/tv"
  persistentVolumeReclaimPolicy: Retain