apiVersion: v1
kind: PersistentVolume
metadata:
  name: youtube-pv
  namespace: servarr
  labels:
    type: local
spec:
  storageClassName: youtube
  capacity:
    storage: 180Ti
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/unraid/youtube"
  persistentVolumeReclaimPolicy: Retain