apiVersion: v1
kind: Service
metadata:
  name: overseerr-srv
  namespace: servarr
spec:
  ports:
  - protocol: TCP
    port: 5055
    targetPort: 5055
  selector:
    app: overseerr
  type: LoadBalancer