apiVersion: v1
kind: Service
metadata:
  name: speed-test-srv
  namespace: servarr
spec:
  ports:
  - protocol: TCP
    port: 8383
    targetPort: 8383
  selector:
    app: speed-test
  type: LoadBalancer