apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: 4k-movies-pvc
  namespace: servarr
spec:
  storageClassName: 4k-movies
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 180Ti
