apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: code-server-pvc
  namespace: servarr
spec:
  storageClassName: code-server
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 180Ti
