apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: downloads-pvc
  namespace: servarr
spec:
  storageClassName: downloads
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Ti
