apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: general-pvc
  namespace: nextcloud
spec:
  storageClassName: general
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 180Ti