apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lidarr-pvc
  namespace: servarr
spec:
  storageClassName: lidarr
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 180Ti