apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: movies-pvc
  namespace: servarr
spec:
  storageClassName: movies
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 180Ti
