apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prowlarr-pvc
  namespace: servarr
spec:
  storageClassName: prowlarr
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 180Ti