apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-pvc
  namespace: servarr
spec:
  storageClassName: radarr
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 180Ti