apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: speed-test-pvc
  namespace: servarr
spec:
  storageClassName: speed-test
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 180Ti