apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tv-pvc
  namespace: servarr
spec:
  storageClassName: tv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 180Ti
