apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: youtube-pvc
  namespace: servarr
spec:
  storageClassName: youtube
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 180Ti
